### ISSUE TITLE
Add AppleStrategy

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/remix-auth#10]

**Comment by lgastler** [comment]
Hi everyone 👋, 

I have been working on "Sign In with Apple" for the last few days and managed to set up a working strategy. 

Of course Apple does some things different than the "classic" OAuth flow. But I think I found an acceptable solution to integrate the whole thing into the existing OAuth strategy without having to adapt it.

I will create the documentation and an example and make a PR, I am curious what you think about my solution.

**Comment by sergiodxa** [comment]
I'm closing this since strategies are not going to be part of the Remix Auth package and they should be published independently.
