### ISSUE TITLE
Add TwitterStrategy

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/remix-auth#11]

**Comment by ilangorajagopal** [comment]
Hey Sergio,

I'd like to take a stab at this issue if it's not already taken?

**Comment by sergiodxa** [comment]
> Hey Sergio,
> 
> I'd like to take a stab at this issue if it's not already taken?

No one is working on it

**Comment by camiaei** [comment]
Hi @ilangorajagopal is there any news about this? It would be great to have this feature 😀

**Comment by sergiodxa** [comment]
@camiaei since v3 strategies do not live in this package anymore so it will be up to the community to build one, the [remix-auth-socials](https://github.com/TheRealFlyingCoder/remix-auth-socials) package has plans to support it.
