### ISSUE TITLE
User is not logged in when verify data contains UTF-8 characters

### ISSUE THREAD

**Issue by thangngoc89** [sergiodxa/remix-auth#115]
### Describe the bug

When the data returns from verify function contains UTF-8, cookie is set, authenticator redirects to `successRedirect` but user isn't logged in.

### Your Example Website or App

https://github.com/thangngoc89/remix-auth/commit/73c6ed2c4b6fe723b2d67be248b780b1763bd2bd

### Steps to Reproduce the Bug or Issue

1. Clone https://github.com/thangngoc89/remix-auth/
2. `git checkout utf8-bug` 
3. `cd examples/local`
4. npm run dev
5. Go to http://localhost:3000
6. Click on login
7. Enter password `abc123` and click login

### Expected behavior

User should be logged in. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

---
Update: I've tracked this error to this line https://github.com/remix-run/remix/blob/a69a631cb5add72d5fb24211ab2a0be367b6f2fd/packages/remix-server-runtime/cookies.ts#L156

Since atob and btoa require that data must be Latin1 encoding, putting utf-8 data inside the cookie session would throw. I'm not sure why remix has silenced this error but I think this isn't a remix-auth's error

Suggestions on how to fix this is available at https://stackoverflow.com/a/26603875

**Comment by nimaa77** [comment]
it seems remix uses `btoa` and `atob` functions to encode and  decode the data. and these function dosen't support utf8 ...

there is solution for it in [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/btoa#unicode_strings)

**Comment by sergiodxa** [comment]
Since this seems to be a Remix bug and not a Remix Auth bug I will close this issue, the progress can be track in the issue opened in the Remix repo.
