### ISSUE TITLE
LocalStrategy not found

### ISSUE THREAD

**Issue by hgeldenhuys** [sergiodxa/remix-auth#129]
### Describe the bug

Following the example code for Local Strategy, the import for LocalStrategy is missing or not found using 
`import { Authenticator, LocalStrategy } from "remix-auth";`

https://github.com/sergiodxa/remix-auth/blob/68d3cf6e57859252b507f0d210a27f7935317a42/examples/local/app/services/auth.ts#L1

### Your Example Website or App

examples/local

### Steps to Reproduce the Bug or Issue

Install npm packages and try to run the app

### Expected behavior

Compiler should not complain about missing import

### Screenshots or Videos

<img width="1009" alt="Screen Shot 2022-01-22 at 3 18 55 PM" src="https://user-images.githubusercontent.com/179999/150654185-6dd87254-8425-4e8d-a254-b2059addfc09.png">

### Platform

- OS: macOS
- Browser: Chrome, Brave (but N/A)
- Version: N/A

**Comment by nkrmr** [comment]
LocalStrategy change to FormStrategy with 'remix-auth-form'

```
import { FormStrategy } from "remix-auth-form";

// Tell the Authenticator to use the form strategy
authenticator.use(
  new FormStrategy(async ({ form }) => {
    let email = form.get("email");
    let password = form.get("password");
    let user = await login(email, password);
    // the type of this user must match the type you pass to the Authenticator
    // the strategy will automatically inherit the type if you instantiate
    // directly inside the `use` method
    return user;
  }),
  // each strategy has a name and can be changed to use another one
  // same strategy multiple times, especially useful for the OAuth2 strategy.
  "user-pass"
);
```

**Comment by sergiodxa** [comment]
Strategies are not exported from the remix-auth package but from individual packages, the LocalStrategy was also replaced by the [FormStrategy](https://github.com/sergiodxa/remix-auth-form)
