### ISSUE TITLE
userProfile method is protected even though it's an easy way to access user info

### ISSUE THREAD

**Issue by EdenTurgeman** [sergiodxa/remix-auth#205]
### Describe the bug

I would love to be able to access the `userProfile` method in my remix app to identify the currently logged in user.
Auth0-js has this functionality built in the client and i think we should expose it here unless i'm missing something

### Your Example Website or App

https://stackblitz.com/none

### Steps to Reproduce the Bug or Issue

![image](https://user-images.githubusercontent.com/12447231/204134944-69bacf8d-0132-4747-8366-6efb716559e3.png)

### Expected behavior

I would love to have an easy way to get the use info from the auth0 strategy/authenticator

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sergiodxa** [comment]
You get that information when the verify callback you pass to the strategy is called

There you can do whatever you want with the data, including returning it so it’s going to be accessible when calling isAuthenticated
