### ISSUE TITLE
Form Data can not be accessed when calling `authenticator.authenticate`

### ISSUE THREAD

**Issue by fkrauthan** [sergiodxa/remix-auth#207]
### Describe the bug

I am trying to implement some additional processing on top of `authenticator.authenticate` that requires me to access `formData` before calling `authenticate`. However, given that formData can only be read once it errors out during the `authenticate` call.

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

1. Call `await request.formData();`
2. Call `await authenticator.authenticate('form-login', request, {});`

### Expected behavior

It works fine and logs me in (and/or allows me to pass in the already parsed `formData`)

### Platform

- OS: Windows and Macos
- Browser: All Browsers
- Version: All Versions

**Comment by sergiodxa** [comment]
You need to clone the request before calling `authenticator.authenticate` if you plan to read the FormData
```ts
let formData = await request.clone().formData()
await authenticator.authenticate('strategy', request, options);
```

**Comment by fkrauthan** [comment]
Ah cool, I will give that a try. Might be worth documenting as the error you get is not very obvious and especially in cases like password reset or activation this might be a sort of common use-case.
