### ISSUE TITLE
Can't use getSession in root

### ISSUE THREAD

**Issue by CSFlorin** [sergiodxa/remix-auth#222]
### Describe the bug

Trying to use `await getSession(request.headers.get("cookie"))` in the app root.tsx and then calling `await authenticator.isAuthenticated(request)` in the main route throws the error:

```
TypeError: Cannot read properties of undefined (reading 'getSession')
    at Authenticator.isAuthenticated (/Users/u/project/node_modules/remix-auth/build/authenticator.js:96:41)
```

which is this line:

```
await this.sessionStorage.getSession(request.headers.get("Cookie"))
```

because `this.sessionStorage` is undefined.

It seems this tries to run on the client for some reason or something.

If you call `await authenticator.isAuthenticated(await getSession(request.headers.get("Cookie")))` instead, it works.

### Your Example Website or App

https://stackblitz.com/edit/node-th5aqr?file=app%2Fsession.server.ts,app%2Fauth.server.ts,app%2Froot.tsx

### Steps to Reproduce the Bug or Issue

1. Visit app
2. Throw error

### Expected behavior

No error

### Platform

- OS: macOS
- Browser: Chrome
- Version: 3.4.0

**Comment by CSFlorin** [comment]
Never mind. This solved my issue: https://discord.com/channels/770287896669978684/920057808127418368/961552673977532486

**Comment by caiocmpaes** [comment]
Hi, @CSFlorin ! I was just having the same issue and came here to search for this...

What's the solution that you found? This Discord Link doesn't seem to work for me 🤔 

I'm curious to know what I'm doing wrong too.

**Comment by caiocmpaes** [comment]
Neverming, @CSFlorin . I joined the Remix Discord Server and found the thread about this.

**Comment by Artmann** [comment]
For people that might stumble upon this thread in the future. There is a race condition due to a cyclic dependency between '~/services/auth.server' and '~/services/session.server'. 

Moving the `requireUser` function from `session` to `auth` solves the problem.
