### ISSUE TITLE
"State doesn't match" authorization error after POST status 302(redirect) in the OAuth2 flow

### ISSUE THREAD

**Issue by cipinistor** [sergiodxa/remix-auth#24]
Hi,
Thank you for this package, it is very useful.
I found an issue while using it with AWS Cognito.

After a POST with status 302(redirect) in the OAuth2 flow, the redirect location url has the "state" parameter already decoded and will not match anymore the session state.

I think the correct fix is to encode/decode state when set-to/get-from URLSearchParams but not encode it in the session.
This will work with in any situation, decoding an already decoded value is the same.

```
async authorize(sessionStorage, session) {
  let state = randomBytes(100).toString("base64");
  session.set(this.sessionStateKey, state);
  ...
  params.set("state", encodeURIComponent(state));
  ...
}

async authenticate(request, sessionStorage, options, callback) {
  ...
   let state = url.searchParams.get("state");
  if (!state)
        throw new AuthorizationError("Missing state.");
  state = decodeURIComponent(state);
  
  if (session.get(this.sessionStateKey) === state) {
  ...
}
```

**Comment by casoetan** [comment]
Hey @sergiodxa, thanks for a great project!

I still get this issue with the example auth0 application. Not sure why thou

**Comment by sergiodxa** [comment]
Could you create a reproduction repo with the cognito strategy?

**Comment by casoetan** [comment]
Never mind, I noticed the issue. 

```js
import { createCookieSessionStorage } from "remix";

export let sessionStorage = createCookieSessionStorage({
  cookie: {
    name: "_session",
    domain: 'dwive.com',  // adding this cause the error
    sameSite: "lax",
    path: "/",
    httpOnly: true,
    secrets: ["s3cr3t"],
    secure: process.env.NODE_ENV === "production",
  },
});

export let { getSession, commitSession, destroySession } = sessionStorage;

```

**Comment by KubaJastrz** [comment]
I'm pretty new to Remix and its session system, but after a brief debugging, I noticed that when using cookie sessions with certain cookie config, the `session.get(this.sessionStateKey)` returns `undefined` after coming back from the auth redirect.
https://github.com/sergiodxa/remix-auth/blob/ccd9614a73dafde637d34bf0a5e58468d7938255/src/strategies/oauth2.ts#L147

It might be caused by the fact that the session is not found/persisting after redirection.

This code works for me at the moment:
```ts
const sessionCookie = createCookie('__session', {
  path: '/',
});

export const sessionStorage = createFileSessionStorage({
  dir: '/tmp/remix-session',
  cookie: sessionCookie,
});
```

**Comment by ngbrown** [comment]
If the cookie `sameSite` isn't defined, I think Remix defaults to `strict` which is going to also have this behavior.
