### ISSUE TITLE
bug: not usable with remix latest upgrade (v2.0)

### ISSUE THREAD

**Issue by theosenoussaoui** [sergiodxa/remix-auth#242]
### Describe the bug

Remix was updating on the 15th of September, and we haven't been able to upgrade because of the peerDependencies `remix-auth` has. More precisely, `remix-auth` needs a version bump for the `@remix-run/react` package.

### Your Example Website or App

https://github.com/theosenoussaoui/remix-auth-bug-report

### Steps to Reproduce the Bug or Issue

- Clone the provided repo.
- Try to `npm install`.

### Expected behavior

Should work with the latest `@remix-run` packages.

### Platform

- Any platform.

**Comment by caprica** [comment]
> That lets it install, but I haven't had a chance to test functionality yet.

Did you encounter any problems yet with this? I'd also like to upgrade my project to 2.0.

**Comment by Scott-Fischer** [comment]
I don't see why there would be any problems. I've been using this package with all the remix v2 flags for a few months now. Seems like the peer dependency just needs to be loosened to account for the new version.

**Comment by jackbravo** [comment]
I think this was solved with the release of [3.6.0](https://github.com/sergiodxa/remix-auth/releases/tag/v3.6.0) a few hours ago :-)
