### ISSUE TITLE
Documentation still references CatchBoundary

### ISSUE THREAD

**Issue by bluefire2121** [sergiodxa/remix-auth#270]
### Describe the bug

The documentation still references CatchBoundary as an method to handle errors. CatchBoundary is a Remix v1 feature. Remix v2 uses the ErrorBoundary for both 400 and 500 errors. Can the documentation be updated?

### Your Example Website or App

Docs

### Steps to Reproduce the Bug or Issue

Read Error section of docs.

### Expected behavior

ErrorBoundary is the correct method in Remix v2.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sergiodxa** [comment]
I re-wrote docs and there's no reference to CatchBoundary anymore
