### ISSUE TITLE
Session persists after user deletion, causing errors

### ISSUE THREAD

**Issue by 684efs3** [sergiodxa/remix-auth#294]
### Describe the bug

When a user is authenticated but their data is subsequently deleted from the database, the application throws errors instead of gracefully logging the user out. The session persists in the user's cookies, causing the app to assume the user is still authenticated when they are not.

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Authenticate a user using any strategy (e.g., TOTP, Google OAuth).
2. Manually delete the user's data from the database.
3. Attempt to access a protected route or perform an action that requires authentication.

### Expected behavior

The website should not show an error, and instead, delete the cookies from the browser. 

### Platform

- MacOS
- Chrome
- remix-auth 3.7.0

### Additional context

When the cookies are manually deleted, there is no error.

**Comment by GoldenretriverYT** [comment]
why should remix auth handle this and not you yourself?

**Comment by sergiodxa** [comment]
Remix Auth has no access to your DB, there's no way to know the user was deleted.

The only thing Remix Auth can do is to check if the session has the user data you stored there.

If you want it to work automatically change from createCookieSessionStorage to a DB-backed custom session storage, then if you delete the user delete the session data in your DB too.

This way, the next time Remix Auth tries to access the session it will be null and consider the user unauthenticated.
