### ISSUE TITLE
Cloudflare KV Session Storage not working.

### ISSUE THREAD

**Issue by saibotrellum** [sergiodxa/remix-auth#300]
Hey,
I can't get Cloudflare KV session storage to work in a test install (after having problems updating working project). 

Am stupid? Did find bug? 

### Steps to Reproduce the Bug or Issue

- Take a current, fresh remix cloudflare install (2.12.1)
(`npx create-remix@latest --template remix-run/remix/templates/cloudflare`)
-  add a wrangler.toml with cloudflare bindings, remix-auth (3.7.0) and remix-auth-form(1.5.0) and make sure it runs `npm run dev`
- add a loader with

```
export const loader = async ({request, context}) => {
// TEST KV FUNTIONALITY, WRITE->READ TO KV

  console.log(''context.cloudflare.env.KV_SESSION_DEFAULT)
  await context.cloudflare.env.KV_SESSION_DEFAULT.put('test','text')
  await console.log(await context.cloudflare.env.KV_SESSION_DEFAULT.get('test'))
};
```

produces in console:

```
KV BINDING: ProxyStub { name: 'KvNamespace', poisoned: false } // OK, vite knows about KV binding

KV BINDING: text //  AND writing/reading to KV works

```

So: KV itself works.
Replacing loader with

```
export const loader = async ({request, context}) => {
  //GET USER SESSION
  const authenticator =await getAuth(context)
  const userSession = await  authenticator.isAuthenticated(request);
  console.log('session', userSession)
  return false;
};
```
produces in console:
```
TypeError: this.sessionStorage.getSession is not a function // HOWEVER using KV with authenticator doesn't 
```

Why?
The authenticator is instantiated by

```
 const authenticator = 
   new Authenticator<TUserSession | Error | null>(context.cloudflare.env.KV_SESSION_DEFAULT, {
        sessionKey: "sessionKey", // keep in sync
        sessionErrorKey: "sessionErrorKey", // keep in sync
    });
```

So, the same, working (above) KV, but remix-auth stays angry and just won't take it anymore.

Anyone can help? 

### Expected behavior

No errors

### Platform

macOS

**Comment by sergiodxa** [comment]
What is `context.cloudflare.env.KV_SESSION_DEFAULT`? It has to be a SessionStorage object.

**Comment by saibotrellum** [comment]
Makes sense, now that you say it.
Fixed and works.

Don't know what I merged or rewrote there.

Anyway, it does what I want. Thanks!
