### ISSUE TITLE
Support passing additional information to the Strategy for use during Verify

### ISSUE THREAD

**Issue by danalloway** [sergiodxa/remix-auth#35]
I have a use-case where my datasource / service instance lives on the Remix AppContext object and is not available when the auth strategy gets initialized.

I would like to be able to pass in some additional parameters from the action/loader when I call `auth.authenticate()` and then make those parameters available on the `verify` function call

**Comment by sergiodxa** [comment]
It has been a long time, but I just merged #113 which let strategies receive the context as an option from the `authenticate` method, so you can do:
```ts
export let action: ActionFunction = async ({ request, context }) => {
  return await authenticator.authenticate("strategy", request, {
    context, // this is new
    successRedirect: "/",
    failureRedirect: "/login"
  })
}
