### ISSUE TITLE
Add Web Authentication API support

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/remix-auth#43]
Remix Auth should have a way to support using the [Web Authentication API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API) somehow, or at an example or guide.

- [x] #44
- [ ] #45
- [ ] #47

**Comment by armandabric** [comment]
I was looking to implement web authentication and found this package https://github.com/alexanderson1993/remix-auth-webauthn

**Comment by sergiodxa** [comment]
I have decided this is out of the scope of Remix Auth
