### ISSUE TITLE
Consider shipping each strategy separately

### ISSUE THREAD

**Issue by edmundhung** [sergiodxa/remix-auth#52]
While I am working on #49, it feels like there will always be case that works only on some environments. It might requires node package that cannot polyfill or depends on package specific to certain platforms.

All strategies are bundled together at the moment. But maybe it worth consider shipping them separately: 
Either (1) As independent package or (2) As subfolders (i.e. `import { LocalStrategy } from "remix-auth/strategies/LocalStrategy";`

**Comment by sergiodxa** [comment]
From v2.4.0 you can do:

```ts
import { Authenticator } from "remix-auth/build/authenticator"
import { LocalStrategy } from "remix-auth/build/strategies/local"
```

Treat it as a non documented behavior from now, in a future version I will remove the `build` from the path.
