### ISSUE TITLE
GitHubStrategy example crashes app

### ISSUE THREAD

**Issue by juhanakristian** [sergiodxa/remix-auth#55]
The GitHubStrategy example in [docs](https://github.com/sergiodxa/remix-auth/blob/83fc5d8494f4ac9ac6ee55fe7505379a6668248b/docs/strategies/github.md) crashes the application with error `Error: Promise rejected with value` when clicking login.

![image](https://user-images.githubusercontent.com/544386/142699395-075d5a52-4a10-46fd-bc87-b4d41f02a90b.png)

Seems like the fix is to return the value of `authenticator.authenticate` in `app/routes/auth/github.tsx`

```
export let action: ActionFunction = ({ request }) => {
  return authenticator.authenticate("github", request);
};
```

Also the loader in `app/routes/auth/github/calllback.tsx`  needs to be changed to return the value of `authenticator.authenticate`

```
export let loader: LoaderFunction = ({ request }) => {
  return authenticator.authenticate("github", request, {
    successRedirect: "/dashboard",
    failureRedirect: "/login",
  });
};
```

Tested with Remix 0.20.1.

I'd be happy to create a PR for this!

**Comment by sergiodxa** [comment]
Ahh you need to either return the value or await it making the loader/action an async function, if you want to send a PR to fix it I can merge it, if not I will send a PR in a few minutes.
