### ISSUE TITLE
Identity Provider

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/remix-auth#63]
Remix Auth could not only give you a way to authenticate users against a third party service using oAuth2, it could also give you everything to become a identity provider using oAuth2 yourself, allowing you to expose the required endpoints for someone to login with your app.

**Comment by ngbrown** [comment]
Sounds like too many concerns in a single package.

**Comment by sergiodxa** [comment]
> Sounds like too many concerns in a single package.

Maybe? It's still related to auth tho, but it could be a `remix-idp` package or something like that too.

It may be even better that way, I haven't really started to think about this aside of the comment on the issue.

**Comment by suzy-g38** [comment]
Hey @sergiodxa, Is this issue ongoing? I'd love to collaborate and help you on this issue .

**Comment by sergiodxa** [comment]
I still want to do it eventually, I just haven't had the time to work on it, if you need a solution right now there's a popular Node package here https://github.com/panva/node-oidc-provider

**Comment by suzy-g38** [comment]
Hi @sergiodxa,

Thanks for the suggestion. Actually, I recently worked on an Authentication Provider for my company using the node-oidc-provider by panva, which you mentioned. and I started getting interested in authentication libraries. I've always wanted to contribute to Remix, and when I found out about Remix-Auth, it felt like the perfect opportunity. I'd love to help with this issue and contribute to the project. 
Let me know if you need any help.

**Comment by sergiodxa** [comment]
I have decided this is out of the scope of Remix Auth, I may revisit this idea in the future as a separate package.
