### ISSUE TITLE
Add FacebookStrategy

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/remix-auth#8]
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/

**Comment by chadelofson** [comment]
Hi @sergiodxa, I would like to try and tackle this issue.

**Comment by sergiodxa** [comment]
@chadelofson I recommend you to check how the [GoogleStrategy](https://github.com/sergiodxa/remix-auth/blob/main/src/strategies/google.ts) works, it will probably be similar, just change the URLs and how to get the user profile

**Comment by chadelofson** [comment]
@sergiodxa ok, I have been looking at both Google and GitHub strategies.  

For the google strategy, how did you determine what to use for GoogleStrategyOptions and GoogleExtraParams?

**Comment by sergiodxa** [comment]
@chadelofson the StrategyOptions is anything you may need from the developer or the developer may be able to set, example, when using Google you need a client id and secret and you need a callback URL (usually called redirect_uri in the docs of the services), but the developer can also set more things like the scope, access type, etc., those are all used in the `authorizationParams` to pass them in the URL.

For the ExtraParams, this is whatever the provider returned after getting the token, if you see here https://github.com/sergiodxa/remix-auth/blob/main/src/strategies/oauth2.ts#L245-L256, that `getAccessToken` method is called from `fetchAccessToken`, by default (GoogleStrategy uses the default, GitHubStrategy overwrote it) it parses the response of `fetchAccessToken` as JSON, get the access_token and refresh_token and anything else returned in that response is called ExtraParam, so you need to see what the provider return here and add it to the interface.

**Comment by sergiodxa** [comment]
I'm closing this since strategies are not going to be part of the Remix Auth package and they should be published independently.

**Comment by chadelofson** [comment]
ok, sounds good.   So what should the package names be called?

**Comment by sergiodxa** [comment]
I recommend `remix-auth-facebook`

**Comment by chadelofson** [comment]
OK, thank you.  Same folder structure as what you had?  Do you have other strategies moved to their own project?

**Comment by pbteja1998** [comment]
@chadelofson you can use https://github.com/sergiodxa/remix-auth-strategy-template as a base.

**Comment by chadelofson** [comment]
@pbteja1998 thanks!
